# Generated by Django 3.2.16 on 2022-11-14 13:05

import bsct.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Área')),
                ('apelido', models.CharField(default='', max_length=10, unique=True, verbose_name='Apelido da Área')),
                ('tempo_resposta', models.IntegerField(default=72, verbose_name='Tempo de Resposta (horas)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('segundo_responsavel', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='segundo', to=settings.AUTH_USER_MODEL, verbose_name='Segundo Responsável')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'ordering': ['id'],
            },
            bases=(bsct.models.BSCTModelMixin, models.Model),
        ),
    ]
